### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by liamtarpey** [homerjam/angular-cropify#1]
Another great directive :)

Encountered 2 issues implementing this into a page with a vertical scrollbar: 
- the mask starts drawing lower than the actual mouse Y position (lower by the value of scrollY)
- moving the mask would cause it to jump upwards by the value of scrollY

Fixed these by editing the following lines:

**298:** (cropStart function)

``` javascript
var yy = e.pageY - $window.scrollY; 
```

**411:** (dragStart function)

``` javascript
ctrl.offsets.crop.top = e.offsetY + $window.scrollY; 
```

**Comment by homerjam** [comment]
Sweet! How about a PR? : )

**Comment by liamtarpey** [comment]
Will submit one shortly :)
